apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mysql-secret
  data:
    - secretKey: MYSQL_USERNAME
      remoteRef:
        key: production/myapp/mysql
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: production/myapp/mysql
        property: password
    - secretKey: MYSQL_HOST
      remoteRef:
        key: production/myapp/mysql
        property: host
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: production/myapp/mysql
        property: database
