pipeline {
    agent any

    environment {
        APP_DIR  = "./Green"
        IMAGE    = "sohampatil08/picnic-app"
        BLUE_CONTAINER  = "picnic-Blue"
        GREEN_CONTAINER = "picnic-Green"
        BLUE_PORT       = "8081"
        GREEN_PORT      = "8082"
    }

    stages {
        stage ('checkout') {
            steps {
                    git branch: 'main',
                    url: 'https://github.com/sohampatil8/blue-green-deployment.git'
            }
        }

        stage ('Build Docker Image') {
            steps {
                sh '''
                    echo "Building Docker image..."

                    docker build \
                        -t $IMAGE:$BUILD_NUMBER \
                        -t $IMAGE:Green \
                        $APP_DIR
                '''
            }
        }

        stage ('Docker Login & Push Image') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-creds',
                        usernameVariable: 'DOCKER_USERNAME',
                        passwordVariable: 'DOCKER_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login \
                            -u "$DOCKER_USERNAME" \
                            --password-stdin

                        docker push $IMAGE:$BUILD_NUMBER
                        docker push $IMAGE:Green
                    '''
                }
            }
        }

        stage('Deploy Green') {
            steps {
                sh '''
                    echo "Deploying Green container..."

                    docker rm -f $GREEN_CONTAINER || true

                    docker run -d \
                        --name $GREEN_CONTAINER \
                        -p $GREEN_PORT:80 \
                        $IMAGE:$BUILD_NUMBER
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                sh '''
                    echo "Verifying deployment..."

                    sleep 5

                    docker ps \
                        --filter "name=$GREEN_CONTAINER" \
                        --filter "status=running"
                '''
            }
        }

        stage('Remove Blue') {
            steps {
                sh '''
                    echo "Removing BLUE container..."

                    docker rm -f $BLUE_CONTAINER || true

                    echo "BLUE container removed."
                '''
            }
        }
    }

    post {
        success {
            echo 'Green deployment successful!'
        }

        failure {
            echo 'Green deployment failed!'
        }

        always {
            sh 'docker logout || true'
        }
    }
}